### ISSUE TITLE
initSL vs tailSL

### ISSUE THREAD

**Issue by arademaker** [emap-ed-20242/fad#48]
```
#eval fromSL $ SymList.mk [1] [3,2] (by simp) -- [1,2,3]
#eval (tailSL $ SymList.mk [1] [3,2] (by simp)) >>= pure ∘ fromSL -- some [3,2]
#eval (initSL $ SymList.mk [1] [3,2] (by simp)) >>= pure ∘ fromSL -- some [1,2]
```

A segunda saída está errada. Bug reportado ao @nicolasspaniol !

**Comment by arademaker** [comment]
voluntário para corrigir?  possíveis soluções:

1. tentar ser mais genérico dizendo que dada uma lista, sempre podemos dividir em duas de forma a eles serem componentes válidos de uma SymList
2. criar duas funções `splitInTwoSL` ao invés de apenas uma.

**Comment by nicolasspaniol** [comment]
O initSL está certo não? parece que nesse caso só faltou um reverse da lista retornada no tailSL. vou dar uma olhada logo mais de qualquer jeito

**Comment by arademaker** [comment]
Vc diz reverter a entrada? Pode funcionar…

**Comment by nicolasspaniol** [comment]
Acho que não, pelo que eu testei colocar o `.reverse` é suficiente; devo ter esquecido de inverter conforme reescrevia a função

**Comment by arademaker** [comment]
sim, já funcionou aqui, mas a prova da equivalencia de tailSL com tail não está trivial..
